# ============================================================
# Management & Health Check Configuration
# ============================================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    diskspace:
      enabled: true


# ------------------------------------------------------------
# Logging
# ------------------------------------------------------------
logging:
  level:
    root: INFO

    org.springframework.boot: INFO
    org.springframework.web: INFO
    org.springframework.context: INFO
    org.springframework.cloud: INFO

    com.gnax: DEBUG