server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:30432/devdb
    username: ${DB_USER}
    password: ${DB_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true

jwt:
  issuer: gnax-identity-service
  access-token-expiration: 900
  refresh-token-expiration: 604800

gnax:
  jwt:
    issuer: gnax-identity-service
    access-token-ttl: 15m
    refresh-token-ttl: 7d
    private-key: ${JWT_PRIVATE_KEY}
    public-key: ${JWT_PUBLIC_KEY}